Added ENV path for Amazon changes to bucket paths

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,12 +1,14 @@
 #!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir>
+# bin/compile <build-dir> <cache-dir> <env-dir>
+
+env=$(cd "$3/" && pwd)
 
 BUILD_DIR=$1
 CACHE_DIR=$2
 BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
 
-TEXLIVE_DOMAIN="https://heroku-buildpack-tex.s3.amazonaws.com"
-VERSION=`curl $TEXLIVE_DOMAIN/VERSION -s`
+TEXLIVE_DOMAIN=$TEXLIVE_DOMAIN
+VERSION=`curl $TEXLIVE_DOMAIN/PACKAGES-VERSION -s`
 TEXLIVE_URL="$TEXLIVE_DOMAIN/texlive-$VERSION.tar.gz"
 TEXLIVE_HOME=$BUILD_DIR/.texlive
 TEXLIVE_CACHE=$CACHE_DIR/.texlive
@@ -21,42 +23,47 @@ mkdir -p $TEXLIVE_HOME
 mkdir -p $TEXLIVE_CACHE
 mkdir -p `dirname $PROFILE_D`
 
-function test {
-    "$@"
-    local status=$?
-    if [ $status -ne 0 ]; then
-        echo "error with $1" >&2
-    fi
-    return $status
-}
+echo $env
+echo $TEXLIVE_DOMAIN
 
-if [ -f $TEXLIVE_CACHE/VERSION ] && (( $VERSION == `cat $TEXLIVE_CACHE/VERSION` )); then
-    # Get TeX Live from the cache if possible
-    build-step "Copying TeX Package Files from cache: Package $VERSION"
-    cp -R $TEXLIVE_CACHE/* $TEXLIVE_HOME
-else
-    # Get TeX Live from S3 if necessary
-    if [ -f "$TEXLIVE_CACHE/VERSION" ]; then
-        build-step "Upgrading to TeX Live $VERSION"
-    else
-        build-step "Fetching TeX Live $VERSION"
-    fi
+# function test {
+#     "$@"
+#     local status=$?
+#     if [ $status -ne 0 ]; then
+#         echo "error with $1" >&2
+#     fi
+#     return $status
+# }
 
-    curl $TEXLIVE_URL -s -o - | tar xzf - -C $TEXLIVE_HOME
+# if [ -f $TEXLIVE_CACHE/VERSION ] && (( $VERSION == `cat $TEXLIVE_CACHE/VERSION` )); then
+#     # Get TeX Live from the cache if possible
+#     build-step "Copying TeX Package Files from cache: Package $VERSION"
+#     cp -R $TEXLIVE_CACHE/* $TEXLIVE_HOME
+# else
+#     # Get TeX Live from S3 if necessary
+#     if [ -f "$TEXLIVE_CACHE/VERSION" ]; then
+#         build-step "Upgrading to TeX Live $VERSION"
+#     else
+#         build-step "Fetching TeX Live $VERSION"
+#     fi
 
-    # Make sure the cache is empty
-    rm -rf $TEXLIVE_CACHE/*
+#     curl $TEXLIVE_URL -s -o - | tar xzf - -C $TEXLIVE_HOME
 
-    # Store a copy of it in the cache so it doesn't have to be fetched again
-    cp -R $TEXLIVE_HOME/* $TEXLIVE_CACHE
+#     # Make sure the cache is empty
+#     rm -rf $TEXLIVE_CACHE/*
 
-    # Store the version for later
-    echo $VERSION > $TEXLIVE_CACHE/VERSION
-fi
+#     # Store a copy of it in the cache so it doesn't have to be fetched again
+#     cp -R $TEXLIVE_HOME/* $TEXLIVE_CACHE
 
-build-step "Setting Up Package Configuration : Buildling KPathSea Database"
-test mktexlsr
-build-step "Creating Font Mappings"
-test updmap
-build-step "Formatting and Compiling Packages"
-test fmtutil --all
+#     # Store the version for later
+#     echo $VERSION > $TEXLIVE_CACHE/VERSION
+# fi
+
+# build-step "Setting Up Package Configuration : Buildling KPathSea Database"
+# test mktexlsr
+# build-step "Creating Font Mappings"
+# test updmap
+# build-step "Formatting and Compiling Packages"
+# test fmtutil --all
+
+build-step "Copying TeX Package Files from cache: Package $VERSION"
